### ISSUE TITLE
.shd example not working on docs page

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/ignite-docs#1]
Hi, I didn't have a closer look, but there are no shadows on the mixins example page.

**Comment by sveneberth** [comment]
Will be fixed with the next ignite release: https://github.com/viur-framework/ignite/commit/beec1d3ad2bcf3ffb74fd9e1d702d55a31a04893

**Comment by sveneberth** [comment]
Is still not released ...

**Comment by sveneberth** [comment]
Live with today's release. 66ce5f8e44654947621e22bd48fdaf90db9621e9
